services:
  postgres:
    image: postgres
    container_name: postgres-pctools-images
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USER:-pctools-images}
      - POSTGRES_PASSWORD=${DATABASE_PASS:-pctools-images}
      - POSTGRES_DB=${DATABASE_NAME:-pctools-images}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 20s
      retries: 3
volumes:
  postgres:
