name: Install

on: workflow_dispatch

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tools repo
        uses: actions/checkout@v4

      - name: Prepare Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          password: ${{ secrets.SSH_KEY_INSTALL }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            apt update -y
            apt upgrade -y
            apt install -y ca-certificates curl gnupg lsb-release -y
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
            echo  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu  $(lsb_release -cs) stable" | sudo 
            tee /etc/apt/sources.list.d/docker.list > /dev/null
            apt update -y
            apt install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
            adduser dehema -quiet -m
            usermod -aG sudo dehema
            groupadd docker
            usermod -aG docker ${{ secrets.SSH_USERNAME }}
            newgrp docker
      - name: Prepare Server 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            curl -O https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh
            bash install.sh
            source ~/.profile
            nvm ls-remote
            nvm install --lts
            rm -fr install.sh
            npm install --global yarn